/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MultipleDraw;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testGetBall() {
        float x = 50.0f, y = 50.0f;
        Ball ballUnderTest = new Ball(x, y);
        assert ballUnderTest.getX() == x && ballUnderTest.getY() == y : "getX() or getY() are returning wrong values";
    }

    @Test public void testSetBall() {
        float x = 50.0f, y = 50.0f;
        Ball ballUnderTest = new Ball(x, y);
        x = 100.0f;
        y = 100.0f;
        ballUnderTest.setX(x);
        ballUnderTest.setY(y);
        assert ballUnderTest.getX() == x && ballUnderTest.getY() == y : "setX() or setY() are setting wrong values.";
    }
}
